
--INSERT A TODAS LAS TABLAS

--INSERTAR RESGISTRO A LA TABLA BC_BANCOS
INSERT INTO BC_BANCOS(CODIGO,NOMBRE,DIRECCION,RNC) VALUES ('BC0001' ,'POPULAR','AVE. MAXIMO GOMEZ NO.48','111111111');
INSERT INTO BC_BANCOS(CODIGO,NOMBRE,DIRECCION,RNC) VALUES ('BC0002' ,'BAN RESERVAS','AVE. MAXIMO GOMEZ NO.48','222222222');
INSERT INTO BC_BANCOS(CODIGO,NOMBRE,DIRECCION,RNC) VALUES ('BC0003' ,'BANESCO','AVE. MAXIMO GOMEZ NO.48','333333333');
INSERT INTO BC_BANCOS(CODIGO,NOMBRE,DIRECCION,RNC) VALUES ('BC0004' ,'BANCO LEON','AVE. MAXIMO GOMEZ NO.48','444444444');
INSERT INTO BC_BANCOS(CODIGO,NOMBRE,DIRECCION,RNC) VALUES ('BC0005' ,'BANCO DEL CARIBE','AVE. LOS PROCERES','555555555');
INSERT INTO BC_BANCOS(CODIGO,NOMBRE,DIRECCION,RNC) VALUES ('BC0006' ,'BANCO DEL PROGRESO','AVE. 27 DE FEBRERO','666666666');

--INSERTAR REGISTRO A LA TABLA BC_TIPO_DOC_BANCARIOS
INSERT INTO BC_TIPO_DOC_BANCARIOS(CODIGO,NOMBRE,ORIGEN) VALUES ('TJ0001' ,'TARJETA DE DEBITO','D');
INSERT INTO BC_TIPO_DOC_BANCARIOS(CODIGO,NOMBRE,ORIGEN) VALUES ('TJ0002' ,'TARJETA DE CREDITO','C');
INSERT INTO BC_TIPO_DOC_BANCARIOS(CODIGO,NOMBRE,ORIGEN) VALUES ('LB0001' ,'LIBRETA DE AHORRO','D');
INSERT INTO BC_TIPO_DOC_BANCARIOS(CODIGO,NOMBRE,ORIGEN) VALUES ('CK0001' ,'CHEQUE','C');

--INSERTAR REGISTRO A LA TABLA BC_CLIENTES
INSERT INTO BC_CLIENTES (ID_TIPO_DOC_BANCARIO,NUM_DOCUMENTO,NOMBRE,ESTADO) VALUES( 22,'40223370947','JUANA ROMERO','A');
INSERT INTO BC_CLIENTES (ID_TIPO_DOC_BANCARIO,NUM_DOCUMENTO,NOMBRE,ESTADO) VALUES(23,'40223370940','PEDRO ROMAN','I');
INSERT INTO BC_CLIENTES (ID_TIPO_DOC_BANCARIO,NUM_DOCUMENTO,NOMBRE,ESTADO) VALUES(24,'00000000000','JULIAS PEREZ','A');
INSERT INTO BC_CLIENTES (ID_TIPO_DOC_BANCARIO,NUM_DOCUMENTO,NOMBRE,ESTADO) VALUES(26,'00000000001','MARICELA CASTILLO','I');
--
INSERT INTO BC_CLIENTES (ID_TIPO_DOCUMENTO,NUM_DOCUMENTO,NOMBRE,ESTADO) VALUES(27,'00000000001','MARICELA CASTILLO','I');
--PRUBRA DE RELACCION CON TIPO_DOC_BANCARIOS

--INSERTAR REGISTRO EN LA TABLA BC_CUENTAS
INSERT INTO BC_CUENTAS (CODIGO,ESTADO,BALANCE_DB,BALANCE_CR) VALUES ('2000000001','A','300000','0');
INSERT INTO BC_CUENTAS (CODIGO,ESTADO,BALANCE_DB,BALANCE_CR) VALUES ('2000000002','A','300000','0');
INSERT INTO BC_CUENTAS (CODIGO,ESTADO,BALANCE_DB,BALANCE_CR) VALUES ('2000000003','A','300000','0');
INSERT INTO BC_CUENTAS (CODIGO,ESTADO,BALANCE_DB,BALANCE_CR) VALUES ('2000000004','A','300000','0');
INSERT INTO BC_CUENTAS (CODIGO,ESTADO,BALANCE_DB,BALANCE_CR) VALUES ('2000000005','A','300000','0');
INSERT INTO BC_CUENTAS (CODIGO,ESTADO,BALANCE_DB,BALANCE_CR) VALUES ('2000000006','A','300000','0');
INSERT INTO BC_CUENTAS (CODIGO,ESTADO,BALANCE_DB,BALANCE_CR) VALUES ('2000000007','A','300000','0');


--INSERTAR REGISTRO EN LA TABLA BD_DOC_BANCARIOS

INSERT INTO BC_DOC_BANCARIOS (ID_CLIENTE,ID_TIPO_DOC_BANCARIO,ID_CUENTA,ID_BANCO,IMPORTE) 
VALUES (28,23,42,27,2);

INSERT INTO BC_DOC_BANCARIOS (ID_CLIENTE,ID_TIPO_DOC_BANCARIO,ID_CUENTA,ID_BANCO,IMPORTE) 
VALUES (29,24,43,27,2);

INSERT INTO BC_DOC_BANCARIOS (ID_CLIENTE,ID_TIPO_DOC_BANCARIO,ID_CUENTA,ID_BANCO,IMPORTE) 
VALUES (30,26,44,27,2);

INSERT INTO BC_DOC_BANCARIOS (ID_CLIENTE,ID_TIPO_DOC_BANCARIO,ID_CUENTA,ID_BANCO,IMPORTE) 
VALUES (27,22,45,27,2);

--INSERTAR REGISTROS EN LA TABLA BC_MOVIMIENTOS

INSERT INTO BC_MOVIMIENTOS(TIPO_MOVIMIENTO, ID_BANCO,ID_CUENTA,ID_CLIENTE, MONTO) 
VALUES ('TRANSFERENCIA',27,43,27,3000);

INSERT INTO BC_MOVIMIENTOS(TIPO_MOVIMIENTO, ID_BANCO,ID_CUENTA,ID_CLIENTE, MONTO) 
VALUES ('DEPOSITO',27,43,27,4000);

INSERT INTO BC_MOVIMIENTOS(TIPO_MOVIMIENTO, ID_BANCO,ID_CUENTA,ID_CLIENTE, MONTO) 
VALUES ('TRASFERENCIA',28,43,27,4000);

INSERT INTO BC_MOVIMIENTOS(TIPO_MOVIMIENTO, ID_BANCO,ID_CUENTA,ID_CLIENTE, MONTO) 
VALUES ('TRANSFERENCIA',29,43,27,6000);

INSERT INTO BC_MOVIMIENTOS(TIPO_MOVIMIENTO, ID_BANCO,ID_CUENTA,ID_CLIENTE, MONTO) 
VALUES ('TRANSFERENCIA',30,43,27,3000);

--INSERTAR REGISTROS EN LA TABLA BC_SUCURSALES

INSERT INTO BC_SUCURSALES (ID_BANCO,CODIGO,NOMBRE,DIRECCION,TELEFONO,CORREO)
VALUES(26,'BC0001','POPULAR SAN VICENTE','AVE. SAN VICENTE DE PAUL','8099602000','popularsanvicente@popular.com.do');

INSERT INTO BC_SUCURSALES (ID_BANCO, CODIGO,NOMBRE,DIRECCION,TELEFONO,CORREO)
VALUES(27,'BC0002','BAN RESERVAS MEGACENTRO','PLAZA MEGA CENTRO','8099602000','banreservasmega@banreservas.com.do');

INSERT INTO BC_SUCURSALES (ID_BANCO, CODIGO,NOMBRE,DIRECCION,TELEFONO,CORREO)
VALUES(26,'BC0001','POPULAR GUARICANO','AVE. SANCHEZ','8099602000','popularguaricano@popular.com.do');

INSERT INTO BC_SUCURSALES (ID_BANCO, CODIGO,NOMBRE,DIRECCION,TELEFONO,CORREO)
VALUES(26,'BC0001','POPULAR CHARLES','AVE. CHARLES DE GAULLE','8099602000','populacharles@popular.com.do');

INSERT INTO BC_SUCURSALES (ID_BANCO, CODIGO,NOMBRE,DIRECCION,TELEFONO,CORREO)
VALUES(26,'BC0002','BANRESERVAS ZONA COLONIAL','Calle Isabel La Católica','8099602000','banreservascoloniar@banreservas.com.do');

--INSERTAR REGISTROS EN LA BC_TTITULARES_CUENTAS

INSERT INTO BC_TITULARES_CUENTAS (ID_CUENTA,ID_CLIENTE) 
VALUES (42,28);

INSERT INTO BC_TITULARES_CUENTAS (ID_CUENTA,ID_CLIENTE) 
VALUES (43,27);



