
--SELECT PARA MOSTRAR EN FORMULARIO DOC_BANCARIOS
SELECT BC_DOC_BANCARIOS.ID_DOC_BANCARIO, 
       BC_TIPO_DOC_BANCARIOS.CODIGO as CODIGO_BANCO,
       BC_CUENTAS.CODIGO as CODIGO_CUENTA,
       BC_CLIENTES.ID_CLIENTE as ID_CLIENTE,
       BC_BANCOS.CODIGO,
       BC_DOC_BANCARIOS.IMPORTE,
       BC_DOC_BANCARIOS.FECHA
FROM BC_DOC_BANCARIOS 
    INNER JOIN BC_TIPO_DOC_BANCARIOS 
        ON BC_DOC_BANCARIOS.ID_TIPO_DOC_BANCARIO = BC_TIPO_DOC_BANCARIOS.ID_TIPO_DOC_BANCARIO
    INNER JOIN BC_CUENTAS 
        ON BC_DOC_BANCARIOS.ID_CUENTA=BC_CUENTAS.ID_CUENTA
    INNER JOIN BC_CLIENTES
    ON BC_DOC_BANCARIOS.ID_CLIENTE=BC_CLIENTES.ID_CLIENTE
    INNER JOIN BC_BANCOS  
    ON BC_DOC_BANCARIOS.ID_BANCO=BC_BANCOS.ID_BANCO;
    
--SELECT PARA MOSTRAR EN FORMULARIO CLIENTE   
SELECT BC_CLIENTES.ID_CLIENTE,
       BC_TIPO_DOC_BANCARIOS.CODIGO as TIPOs_DE_DOCUMENTOS,
       BC_CLIENTES.NUM_DOCUMENTO,
       BC_CLIENTES.NOMBRE,
       BC_CLIENTES.ESTADO
FROM BC_CLIENTES 
    INNER JOIN BC_TIPO_DOC_BANCARIOS
    ON BC_CLIENTES.ID_TIPO_DOC_BANCARIO=BC_TIPO_DOC_BANCARIOS.ID_TIPO_DOC_BANCARIO;

--SELECT PARA MOSTRAR EN FORMULARIO SUCURSAL   
SELECT BC_SUCURSALES.ID_SUCURSAL,
       BC_BANCOS.CODIGO as CODIGO_BANCO,
       BC_SUCURSALES.CODIGO as CODIGO_SUCURSAL,
       BC_SUCURSALES.NOMBRE,
       BC_SUCURSALES.DIRECCION,
       BC_SUCURSALES.TELEFONO,
       BC_SUCURSALES.CORREO
FROM BC_SUCURSALES INNER JOIN BC_BANCOS 
ON BC_SUCURSALES.ID_BANCO=BC_BANCOS.ID_BANCO;

--SELECT PARA MOSTRAR EN FORMULARIO TITULAR CUENTA
SELECT BC_TITULARES_CUENTAS.ID_TITULAR_CUENTA,
       BC_CUENTAS.ID_CUENTA,
       BC_CLIENTES.ID_CLIENTE
FROM BC_TITULARES_CUENTAS 
        INNER JOIN BC_CUENTAS
            ON BC_TITULARES_CUENTAS.ID_CUENTA=BC_CUENTAS.ID_CUENTA
        INNER JOIN BC_CLIENTES
            ON BC_TITULARES_CUENTAS.ID_CLIENTE= BC_CLIENTES.ID_CLIENTE;
    
--SELECT PARA MOSTRAR EN FORMULARIO MOVIMIENTOS 

SELECT BC_MOVIMIENTOS.ID_BC_MOVIMIENTO, 
       BC_MOVIMIENTOS.TIPO_MOVIMIENTO,
       BC_BANCOS.ID_BANCO,
       BC_CUENTAS.ID_CUENTA,
       BC_CLIENTES.ID_CLIENTE,
       BC_MOVIMIENTOS.MONTO,
       BC_MOVIMIENTOS.FECHA
FROM BC_MOVIMIENTOS 
    INNER JOIN BC_BANCOS
        ON BC_MOVIMIENTOS.ID_BANCO= BC_BANCOS.ID_BANCO
    INNER JOIN BC_CUENTAS 
        ON BC_MOVIMIENTOS.ID_CUENTA= BC_CUENTAS.ID_CUENTA
    INNER JOIN BC_CLIENTES
    ON BC_MOVIMIENTOS.ID_CLIENTE = BC_CLIENTES.ID_CLIENTE;
    