CREATE SEQUENCE  SEQ_USUARIOS
MINVALUE 0 --VALOR MINIMO
START WITH 1--INICIA EN 1
INCREMENT BY 1--SE INCREMENTA EN 1
;

CREATE SEQUENCE  SEQ_BC_BANCOS
MINVALUE 0 --VALOR MINIMO
START WITH 1--INICIA EN 1
INCREMENT BY 1--SE INCREMENTA EN 1
CACHE 20--GUARDA 20 VALORES EN CACHE PARA MEJOR RENDIMIENTO DE CREACION
;

CREATE SEQUENCE  SEQ_BC_SUCURSALES
MINVALUE 0 --VALOR MINIMO
START WITH 1--INICIA EN 1
INCREMENT BY 1--SE INCREMENTA EN 1
CACHE 20--GUARDA 20 VALORES EN CACHE PARA MEJOR RENDIMIENTO DE CREACION
;

CREATE SEQUENCE  SEQ_BC_CUENTAS
MINVALUE 0 --VALOR MINIMO
START WITH 1--INICIA EN 1
INCREMENT BY 1--SE INCREMENTA EN 1
CACHE 20--GUARDA 20 VALORES EN CACHE PARA MEJOR RENDIMIENTO DE CREACION
;

CREATE SEQUENCE  SEQ_BC_CLIENTES
MINVALUE 0 --VALOR MINIMO
START WITH 1--INICIA EN 1
INCREMENT BY 1--SE INCREMENTA EN 1
CACHE 20--GUARDA 20 VALORES EN CACHE PARA MEJOR RENDIMIENTO DE CREACION
;

CREATE SEQUENCE  SEQ_TIPO_DOC_BANCARIOS
MINVALUE 0 --VALOR MINIMO
START WITH 1--INICIA EN 1
INCREMENT BY 1--SE INCREMENTA EN 1
CACHE 20--GUARDA 20 VALORES EN CACHE PARA MEJOR RENDIMIENTO DE CREACION
;

CREATE SEQUENCE  SEQ_DOC_BANCARIOS
MINVALUE 0 --VALOR MINIMO
START WITH 1--INICIA EN 1
INCREMENT BY 1--SE INCREMENTA EN 1
CACHE 20--GUARDA 20 VALORES EN CACHE PARA MEJOR RENDIMIENTO DE CREACION
;

CREATE SEQUENCE SEQ_BC_MOVIMIENTOS
MINVALUE 0
START WITH 1--INICIA EN 1
INCREMENT BY 1--SE INCREMENTA EN 1
CACHE 20--GUARDA 20 VALORES EN CACHE PARA MEJOR RENDIMIENTO DE CREACION
;

